"""empty message

Revision ID: b2f8c3cca90c
Revises: 
Create Date: 2021-12-21 18:49:15.716653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2f8c3cca90c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labor_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('labor_code', sa.String(length=5), nullable=False),
    sa.Column('labor_category', sa.String(), nullable=False),
    sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labor_categories')
    # ### end Alembic commands ###
