"""empty message

Revision ID: 91fde1ed2b8b
Revises: 42f7885b4bc6
Create Date: 2021-12-26 16:05:21.904459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91fde1ed2b8b'
down_revision = '42f7885b4bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_associations',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('labor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['labor_id'], ['labor_categories.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'contract_id', 'labor_id')
    )
    op.drop_table('employees_to_contracts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees_to_contracts',
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('labor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name='employees_to_contracts_contract_id_fkey'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='employees_to_contracts_employee_id_fkey'),
    sa.ForeignKeyConstraint(['labor_id'], ['labor_categories.id'], name='employees_to_contracts_labor_id_fkey'),
    sa.PrimaryKeyConstraint('employee_id', 'contract_id', 'labor_id', name='employees_to_contracts_pkey')
    )
    op.drop_table('employee_associations')
    # ### end Alembic commands ###
